name: "@iwsio/eslint-config: PUSH to main"

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/eslint-config/**'

jobs:
  version:
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    concurrency:
      group: 'versioning-automation'
      cancel-in-progress: false
    uses: iwsllc/workflows/.github/workflows/version-as-app.yaml@main
    with:
      ref: main
      use-pnpm: true
      cache: pnpm
      node-version-file: '.nvmrc'
      scope: '@iwsio'
      version-command: npm version patch -w packages/eslint-config || true
      version-workspace: packages/eslint-config
      tag-includes-name: true
    secrets:
      IWS_VERSION_BOT_PK: ${{ secrets.IWS_VERSION_BOT_PK}}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish:
    needs: version
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: iwsllc/workflows/.github/workflows/publish.yaml@v4
    with:
      ref: main
      use-pnpm: true
      cache: pnpm
      node-version-file: '.nvmrc'
      scope: '@iwsio'
      registry-url: 'https://registry.npmjs.org'
      install-command: 
      build-command: 
      publish-command: pnpm -F eslint-config publish --access public
    secrets:
      # This token is used for reading npm packages; use when private packages are used
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
