name: "@iwsio/fetch: PUSH to main"

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/fetch/**'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  tests:
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: iwsllc/workflows/.github/workflows/test.yaml@v4
    with:
      registry-url: 'https://registry.npmjs.org'
      scope: '@iwsio'
      use-pnpm: true
      cache: pnpm
      node-version-file: '.nvmrc'
      install-command: pnpm install
      test-command: pnpm -F fetch test
  version:
    needs: tests
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    concurrency:
      group: 'versioning-automation'
      cancel-in-progress: false
    uses: iwsllc/workflows/.github/workflows/version-as-app.yaml@main
    with:
      ref: main
      registry-url: 'https://registry.npmjs.org'
      use-pnpm: true
      cache: pnpm
      node-version-file: '.nvmrc'
      scope: '@iwsio'
      version-command: npm version patch -w packages/fetch || true
      version-workspace: packages/fetch
      tag-includes-name: true
    secrets:
      IWS_VERSION_BOT_PK: ${{ secrets.IWS_VERSION_BOT_PK}}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish:
    needs: version
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    uses: iwsllc/workflows/.github/workflows/publish.yaml@v5
    with:
      ref: main
      registry-url: 'https://registry.npmjs.org'
      use-pnpm: true
      skip-node-auth: true
      cache: pnpm
      node-version-file: '.nvmrc'
      scope: '@iwsio'
      install-command: pnpm install
      build-command: pnpm -F fetch build
      publish-command: pnpm -F fetch publish --access public
    secrets:
      # This token is used for reading npm packages; use when private packages are used
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
