name: "@iwsio/fetch: PR to main"

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - 'packages/fetch/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  testing:
    if: ${{github.event.pull_request.draft == false && !contains(github.event.head_commit.message, '#skip') }}
    uses: iwsllc/workflows/.github/workflows/test.yaml@v4
    with:
      registry-url: 'https://registry.npmjs.org'
      scope: '@iwsio'
      use-pnpm: true
      cache: pnpm
      node-version-file: '.nvmrc'
      install-command: pnpm install
      test-command: pnpm -F fetch test